export const iconTypes = {
  "home": 'home',
  "folder": 'folder',
  "keys": 'keys',
  "phone": 'phone',
  "in": 'in',
  "out": 'out',
  "facebook": 'facebook',
  "facebook2": 'facebook2',
  "instagram": 'instagram',
  "telegram": 'telegram',
  "twitter": 'twitter',
  "youtube": 'youtube',
  "whatsapp": 'whatsapp',
  "plus": 'plus',
  "cross": 'cross',
}